#!/bin/bash
### BEGIN INIT INFO
# Provides:          hello_world_go
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Broadcasts "Hello World" UDP messages (Go version)
# Description:       Statically compiled Go extension - no SDK required
### END INIT INFO

# Source function library if it exists
[ -f /etc/init.d/functions ] && . /etc/init.d/functions

SCRIPT_PATH=$(dirname $(realpath $0))
DAEMON_NAME="hello_world_go"
PIDFILE="/var/run/${DAEMON_NAME}.pid"
UDP_PORT="5010"

run_extension() {
    cd ${SCRIPT_PATH}

    local background=$1
    export PORT="${UDP_PORT}"

    if [ "$background" = "true" ]; then
        echo "Starting ${DAEMON_NAME} in background"
        start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} \
                        --exec ./${DAEMON_NAME}
    else
        echo "Starting ${DAEMON_NAME} in foreground"
        ./${DAEMON_NAME}
    fi
}

do_start() {
    DISABLE_AUTO_START="false"
    # check registry for auto-start
    reg_disable_auto_start=$(registry extension ${DAEMON_NAME}-disable-auto-start)
    if [ -n "${reg_disable_auto_start}" ]; then
        DISABLE_AUTO_START=${reg_disable_auto_start}
    fi

    if [ "${DISABLE_AUTO_START}" = "true" ]; then
        echo "Auto-start is disabled for ${DAEMON_NAME}"
        return
    fi
    run_extension true
}

do_stop() {
    start-stop-daemon --stop --pidfile ${PIDFILE}
    rm -f ${PIDFILE}
}

case "$1" in
    start)
        echo "Starting ${DAEMON_NAME}"
        do_start
        ;;
    stop)
        echo "Stopping ${DAEMON_NAME}"
        do_stop
        ;;
    restart)
        echo "Restarting ${DAEMON_NAME}"
        do_stop
        do_start
        ;;
    run)
        echo "Running ${DAEMON_NAME} in foreground"
        run_extension false
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|run}"
        exit 1
        ;;
esac

exit 0
