#!/bin/bash
### BEGIN INIT INFO
# Provides:          time_publisher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Publishes ISO8601 time on UDP
# Description:       Modify port number on startup script
### END INIT INFO

# Source function library if it exists
[ -f /etc/init.d/functions ] && . /etc/init.d/functions

SCRIPT_NAME=start-ext.sh
SCRIPT_PATH=$(dirname $(realpath $0))
DAEMON_NAME="time_publisher"
PIDFILE="/var/run/${DAEMON_NAME}.pid"

do_start() {\
    echo "changeing to ${SCRIPT_PATH} and execing ${0}"
    cd ${SCRIPT_PATH}
    start-stop-daemon --start --background --make-pidfile --pidfile ${PIDFILE} --exec $0 -- run
}

do_stop() {
    start-stop-daemon --stop --pidfile ${PIDFILE}
    rm -f ${PIDFILE}
}

case "$1" in
    start)
        echo "Starting ${DAEMON_NAME}"
        do_start
        ;;
    stop)
        echo "Stopping ${DAEMON_NAME}"
        do_stop
        ;;
    restart)
        echo "Restarting ${DAEMON_NAME}"
        do_stop
        do_start
        ;;
    run)
        cd ${SCRIPT_PATH}
        /bin/bash ./${SCRIPT_NAME}
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|run}"
        exit 1
        ;;
esac

exit 0
